doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
      gedmo_translatable:
        type: annotation
        prefix: Gedmo\Translatable\Entity
        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
        is_bundle: false
    dql:
      numeric_functions:
        power: DoctrineExtensions\Query\Mysql\Power
        cos: DoctrineExtensions\Query\Mysql\Cos
      string_functions:
        find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
        cast: DoctrineExtensions\Query\Mysql\Cast
      datetime_functions:
        date: DoctrineExtensions\Query\Mysql\Date
