controllers:
  resource: ../../src/Controller/
  type: annotation

admin_controllers:
    resource: '../../src/Metrics/Controller'
    type: annotation
    prefix: '/metrics'
    trailing_slash_on_root: false

kernel:
  resource: ../../src/Kernel.php
  type: annotation
